### PR TITLE
feat(file): add copy method

### PR DESCRIPTION
**Pull request by dominicbarnes**
This addresses #32 by adding `File#copy(newPath)` for deep copying a file that can be added to the tree as a distinct file. The copied file has the following alterations made to fit this role:

 1. a new uuid is generated and assigned
 2. the `newPath` is set relative to `file.dirname` and appends to the path history

cc @matthewmueller @darsain

### CODE REVIEW

**Comment by matthewmueller** [comment]
hey sorry late response on this. everything looks great to me except the `appends to the path history`. i've needed to differentiate between `initialPath` and `path` for server-side rendering.

let me share a repo with you so you can have a look.

**Comment by dominicbarnes** [comment]
@matthewmueller what do you want changed exactly? Should `file.history` also be overwritten with `[ newPath ]`? I'm wanting this API to be generic, so the more "exceptions" it makes during the process I feel like undermines that.

Maybe the overall behavior should be customizable via an `options` object?

**Comment by dominicbarnes** [comment]
I can honestly see people wanting different behaviors depending on the context, I'm going to add an `options` object that allows you to customize this.

**Comment by matthewmueller** [comment]
yah, that makes sense to me. actually i just realized that i recently removed the copying file code in favor of another approach, outlined here: https://github.com/matthewmueller/elmo/blob/master/packages/elmo-mako/index.js

i think copying could solve this slight hack that i had to do though.

**Pull request merged**
